-- 코드를 입력하세요
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') PUBLISHED_DATE
FROM BOOK AS B , AUTHOR AS A
WHERE B.AUTHOR_ID = A.AUTHOR_ID AND CATEGORY LIKE "경제"
ORDER BY PUBLISHED_DATE